# File: .github/workflows/workflow.yml

env:
    LOCATION: eastus2
    RESOURCE_GROUP: 'rg-yusuf-akinbade'
    TEMPLATE_FILE: "armtemplates/armserviceplan.json"

on:
  workflow_dispatch:
#on: [push]

name: AzureARMSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Azure ARM Deployment
      #uses: azure/ARM@v1
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group deployment create --name addappserviceplan --resource-group $RESOURCE_GROUP --template-file $TEMPLATE_FILE --parameters storagePrefix=store storageSKU=Standard_LRS

